# Generated by Django 2.2.17 on 2020-11-20 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_gfdhgf_jjh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gfdhgf',
            name='bvcbcbvc7678687868786',
        ),
    ]
